FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 5000
# development mode
ENV FLASK_ENV=development
ENV FLASK_APP=app
ENV FLASK_DEBUG=1
ENV PYTHONUNBUFFERED=1

# Run the entrypoint script
CMD ["sh", "scripts/entrypoint.dev.sh"]
