"""Added redundant game and user in bet for better query performance

Revision ID: 1922a206428b
Revises: 2778023103d3
Create Date: 2025-04-24 23:44:29.785752

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1922a206428b"
down_revision = "2778023103d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("game_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.drop_index("idx_bet_session")
        batch_op.create_index(
            "idx_bet_session", ["session_id", "game_id", "user_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_bet_user", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            "fk_bet_game", "games", ["game_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bets", schema=None) as batch_op:
        batch_op.drop_constraint("fk_bet_user", type_="foreignkey")
        batch_op.drop_constraint("fk_bet_game", type_="foreignkey")
        batch_op.drop_index("idx_bet_session")
        batch_op.create_index("idx_bet_session", ["session_id"], unique=False)
        batch_op.drop_column("user_id")
        batch_op.drop_column("game_id")

    # ### end Alembic commands ###
