"""Enhance game session & bet model

Revision ID: 30229cae655c
Revises: 3f21057a99e3
Create Date: 2025-04-19 11:58:55.089694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30229cae655c'
down_revision = '3f21057a99e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bet_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_bets_per_session', sa.Integer(), nullable=False))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_sessions_per_user', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_bets_per_session', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('max_bets_per_session')
        batch_op.drop_column('max_sessions_per_user')

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_column('max_bets_per_session')
        batch_op.drop_column('bet_count')

    # ### end Alembic commands ###
