"""added betcount and session count to gamepnl

Revision ID: 47a134c2dd54
Revises: 043bfb5ac7ee
Create Date: 2025-05-03 12:26:37.319733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a134c2dd54'
down_revision = '043bfb5ac7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_pnls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bet_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('session_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_pnls', schema=None) as batch_op:
        batch_op.drop_column('session_count')
        batch_op.drop_column('bet_count')

    # ### end Alembic commands ###
