"""Enhanced transaction and wallet and added relation with user

Revision ID: 8fddf89c81cc
Revises: 1922a206428b
Create Date: 2025-04-28 11:17:43.246240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fddf89c81cc'
down_revision = '1922a206428b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('BONUS', 'PENALTY', 'EXPENSE', name='transactioncategory'),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_capital', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('current_balance', sa.Float(), nullable=False))
        batch_op.drop_column('balance')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), nullable=False))
        batch_op.drop_column('current_balance')
        batch_op.drop_column('initial_capital')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.Enum('BONUS', 'PENALTY', 'EXPENSE', name='transactioncategory'),
               type_=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###
