"""Removed enum from transaction category

Revision ID: b0349024db00
Revises: 4023dacd80da
Create Date: 2025-05-22 23:31:23.733819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0349024db00'
down_revision = '4023dacd80da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=postgresql.ENUM('BET', 'WIN', 'BONUS', 'ADMIN_ADJUSTMENT', name='transactioncategory'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('BET', 'WIN', 'BONUS', 'ADMIN_ADJUSTMENT', name='transactioncategory'),
               existing_nullable=False)

    # ### end Alembic commands ###
