"""Added tags and difficulty field for game and netflow for session

Revision ID: efea7e5e68f5
Revises: 8fddf89c81cc
Create Date: 2025-04-29 19:44:16.661244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efea7e5e68f5'
down_revision = '8fddf89c81cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_flow', sa.Float(), nullable=False))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_column('net_flow')

    # ### end Alembic commands ###
